methydackel: "/gpfs3/well/ludwig/users/cfo155/miniconda3/bin/MethylDackel"
fastp: "/gpfs2/well/ludwig/users/cfo155/miniconda2/bin/fastp"
mbiasplot: "/gpfs2/well/ludwig/users/cfo155/02Apr2022/code/mbias_plot.r"

bwa : "BWA/0.7.17-GCC-8.3.0"
fastqc: "FastQC/0.11.9-Java-11"
r : "R/3.6.0-foss-2019a"
trim : "Trim_Galore/0.6.2-GCCcore-8.2.0-Java-11"
matplotlib : "matplotlib/3.1.1-foss-2019b-Python-3.7.4"
picard : "picard/2.23.0-Java-11"
samtools : "samtools/1.8-gcc5.4.0"
python: "Python/3.7.4-GCCcore-8.3.0"


TAG_SMPS: [
  "100_cells_caps",
  "100_cells_taps",
  "10_cells_caps",
  "10_cells_taps",
  "10k_cells_caps",
  "10k_cells_taps",
  "1k_cells_caps",
  "1k_cells_taps",
]
TAG_SMPS_REF: "resource/caps_mm9_lambda.fa"

STD_SMPS: [
  "standard_caps",
  "standard_taps"
]
STD_SMPS_REF: "resource/caps_mm9_lambda.fa"

SCTAPS_SMPS: [
  "scTAPS_i7_1_i5_1_S1",
  "scTAPS_i7_1_i5_2_S2",
  "scTAPS_i7_1_i5_3_S3",
  "scTAPS_i7_1_i5_4_S4",
  "scTAPS_i7_1_i5_5_S5",
  "scTAPS_i7_1_i5_6_S6",
  "scTAPS_i7_1_i5_7_S7",
  "scTAPS_i7_1_i5_8_S8",
  "scTAPS_i7_2_i5_1_S9",
  "scTAPS_i7_2_i5_2_S10",
  "scTAPS_i7_2_i5_3_S11",
  "scTAPS_i7_2_i5_4_S12",
  "scTAPS_i7_2_i5_5_S13",
  "scTAPS_i7_2_i5_6_S14",
  "scTAPS_i7_2_i5_7_S15",
  "scTAPS_i7_2_i5_8_S16",
  "scTAPS_i7_3_i5_1_S17",
  "scTAPS_i7_3_i5_2_S18",
  "scTAPS_i7_3_i5_3_S19",
  "scTAPS_i7_3_i5_4_S20",
  "scTAPS_i7_3_i5_5_S21",
  "scTAPS_i7_3_i5_6_S22",
  "scTAPS_i7_3_i5_7_S23",
  "scTAPS_i7_3_i5_8_S24",
  "scTAPS_i7_4_i5_1_S25",
  "scTAPS_i7_4_i5_2_S26",
  "scTAPS_i7_4_i5_3_S27",
  "scTAPS_i7_4_i5_4_S28",
  "scTAPS_i7_4_i5_5_S29",
  "scTAPS_i7_4_i5_6_S30",
  "scTAPS_i7_4_i5_7_S31",
  "scTAPS_i7_4_i5_8_S32",
  "scTAPS_i7_5_i5_1_S33",
  "scTAPS_i7_5_i5_2_S34",
  "scTAPS_i7_5_i5_3_S35",
  "scTAPS_i7_5_i5_4_S36",
  "scTAPS_i7_5_i5_5_S37",
  "scTAPS_i7_5_i5_6_S38",
  "scTAPS_i7_5_i5_7_S39",
  "scTAPS_i7_5_i5_8_S40",
  "scTAPS_i7_6_i5_1_S41",
  "scTAPS_i7_6_i5_2_S42",
  "scTAPS_i7_6_i5_3_S43",
  "scTAPS_i7_6_i5_4_S44",
  "scTAPS_i7_6_i5_5_S45",
  "scTAPS_i7_6_i5_6_S46",
  "scTAPS_i7_6_i5_7_S47",
  "scTAPS_i7_6_i5_8_S48",
  "scTAPS_i7_7_i5_1_S49",
  "scTAPS_i7_7_i5_2_S50",
  "scTAPS_i7_7_i5_3_S51",
  "scTAPS_i7_7_i5_4_S52",
  "scTAPS_i7_7_i5_5_S53",
  "scTAPS_i7_7_i5_6_S54",
  "scTAPS_i7_7_i5_7_S55",
  "scTAPS_i7_7_i5_8_S56",
  "scTAPS_i7_8_i5_1_S57",
  "scTAPS_i7_8_i5_2_S58",
  "scTAPS_i7_8_i5_3_S59",
  "scTAPS_i7_8_i5_4_S60",
  "scTAPS_i7_8_i5_5_S61",
  "scTAPS_i7_8_i5_6_S62",
  "scTAPS_i7_8_i5_7_S63",
  "scTAPS_i7_8_i5_8_S64",
  "scTAPS_i7_9_i5_1_S65",
  "scTAPS_i7_9_i5_2_S66",
  "scTAPS_i7_9_i5_3_S67",
  "scTAPS_i7_9_i5_4_S68",
  "scTAPS_i7_9_i5_5_S69",
  "scTAPS_i7_9_i5_6_S70",
  "scTAPS_i7_9_i5_7_S71",
  "scTAPS_i7_9_i5_8_S72",
  "scTAPS_i7_10_i5_1_S73",
  "scTAPS_i7_10_i5_2_S74",
  "scTAPS_i7_10_i5_3_S75",
  "scTAPS_i7_10_i5_4_S76",
  "scTAPS_i7_10_i5_5_S77",
  "scTAPS_i7_10_i5_6_S78",
  "scTAPS_i7_10_i5_7_S79",
  "scTAPS_i7_10_i5_8_S80",
  "scTAPS_i7_11_i5_1_S81",
  "scTAPS_i7_11_i5_2_S82",
  "scTAPS_i7_11_i5_3_S83",
  "scTAPS_i7_11_i5_4_S84",
  "scTAPS_i7_11_i5_5_S85",
  "scTAPS_i7_11_i5_6_S86",
  "scTAPS_i7_11_i5_7_S87",
  "scTAPS_i7_11_i5_8_S88",
  "scTAPS_i7_12_i5_1_S89",
  "scTAPS_i7_12_i5_2_S90",
  "scTAPS_i7_12_i5_3_S91",
  "scTAPS_i7_12_i5_4_S92",
  "scTAPS_i7_12_i5_5_S93",
  "scTAPS_i7_12_i5_6_S94",
  "scTAPS_i7_12_i5_7_S95",
  "scTAPS_i7_12_i5_8_S96",
#  "scTAPS_Undetermined_S0"
]
SCTAPS_SMPS_REF: "resource/caps_mm9_lambda.fa"


SCCAPS_SMPS: [
  "C203_N702_i7_10_rev_N502_i5_1_rev",
  "C203_N702_i7_10_rev_N502_i5_2_rev",
  "C203_N702_i7_10_rev_N502_i5_3_rev",
  "C203_N702_i7_10_rev_N502_i5_4_rev",
  "C203_N702_i7_10_rev_N502_i5_5_rev",
  "C203_N702_i7_10_rev_N502_i5_6_rev",
  "C203_N702_i7_10_rev_N502_i5_7_rev",
  "C203_N702_i7_10_rev_N502_i5_8_rev",
  "C203_N702_i7_11_rev_N502_i5_1_rev",
  "C203_N702_i7_11_rev_N502_i5_2_rev",
  "C203_N702_i7_11_rev_N502_i5_3_rev",
  "C203_N702_i7_11_rev_N502_i5_4_rev",
  "C203_N702_i7_11_rev_N502_i5_5_rev",
  "C203_N702_i7_11_rev_N502_i5_6_rev",
  "C203_N702_i7_11_rev_N502_i5_7_rev",
  "C203_N702_i7_11_rev_N502_i5_8_rev",
  "C203_N702_i7_12_rev_N502_i5_1_rev",
  "C203_N702_i7_12_rev_N502_i5_2_rev",
  "C203_N702_i7_12_rev_N502_i5_3_rev",
  "C203_N702_i7_12_rev_N502_i5_4_rev",
  "C203_N702_i7_12_rev_N502_i5_5_rev",
  "C203_N702_i7_12_rev_N502_i5_6_rev",
  "C203_N702_i7_12_rev_N502_i5_7_rev",
  "C203_N702_i7_12_rev_N502_i5_8_rev",
  "C203_N702_i7_1_rev_N502_i5_1_rev",
  "C203_N702_i7_1_rev_N502_i5_2_rev",
  "C203_N702_i7_1_rev_N502_i5_3_rev",
  "C203_N702_i7_1_rev_N502_i5_4_rev",
  "C203_N702_i7_1_rev_N502_i5_5_rev",
  "C203_N702_i7_1_rev_N502_i5_6_rev",
  "C203_N702_i7_1_rev_N502_i5_7_rev",
  "C203_N702_i7_1_rev_N502_i5_8_rev",
  "C203_N702_i7_2_rev_N502_i5_1_rev",
  "C203_N702_i7_2_rev_N502_i5_2_rev",
  "C203_N702_i7_2_rev_N502_i5_3_rev",
  "C203_N702_i7_2_rev_N502_i5_4_rev",
  "C203_N702_i7_2_rev_N502_i5_5_rev",
  "C203_N702_i7_2_rev_N502_i5_6_rev",
  "C203_N702_i7_2_rev_N502_i5_7_rev",
  "C203_N702_i7_2_rev_N502_i5_8_rev",
  "C203_N702_i7_3_rev_N502_i5_1_rev",
  "C203_N702_i7_3_rev_N502_i5_2_rev",
  "C203_N702_i7_3_rev_N502_i5_3_rev",
  "C203_N702_i7_3_rev_N502_i5_4_rev",
  "C203_N702_i7_3_rev_N502_i5_5_rev",
  "C203_N702_i7_3_rev_N502_i5_6_rev",
  "C203_N702_i7_3_rev_N502_i5_7_rev",
  "C203_N702_i7_3_rev_N502_i5_8_rev",
  "C203_N702_i7_4_rev_N502_i5_1_rev",
  "C203_N702_i7_4_rev_N502_i5_2_rev",
  "C203_N702_i7_4_rev_N502_i5_3_rev",
  "C203_N702_i7_4_rev_N502_i5_4_rev",
  "C203_N702_i7_4_rev_N502_i5_5_rev",
  "C203_N702_i7_4_rev_N502_i5_6_rev",
  "C203_N702_i7_4_rev_N502_i5_7_rev",
  "C203_N702_i7_4_rev_N502_i5_8_rev",
  "C203_N702_i7_5_rev_N502_i5_1_rev",
  "C203_N702_i7_5_rev_N502_i5_2_rev",
  "C203_N702_i7_5_rev_N502_i5_3_rev",
  "C203_N702_i7_5_rev_N502_i5_4_rev",
  "C203_N702_i7_5_rev_N502_i5_5_rev",
  "C203_N702_i7_5_rev_N502_i5_6_rev",
  "C203_N702_i7_5_rev_N502_i5_7_rev",
  "C203_N702_i7_5_rev_N502_i5_8_rev",
  "C203_N702_i7_6_rev_N502_i5_1_rev",
  "C203_N702_i7_6_rev_N502_i5_2_rev",
  "C203_N702_i7_6_rev_N502_i5_3_rev",
  "C203_N702_i7_6_rev_N502_i5_4_rev",
  "C203_N702_i7_6_rev_N502_i5_5_rev",
  "C203_N702_i7_6_rev_N502_i5_6_rev",
  "C203_N702_i7_6_rev_N502_i5_7_rev",
  "C203_N702_i7_6_rev_N502_i5_8_rev",
  "C203_N702_i7_7_rev_N502_i5_1_rev",
  "C203_N702_i7_7_rev_N502_i5_2_rev",
  "C203_N702_i7_7_rev_N502_i5_3_rev",
  "C203_N702_i7_7_rev_N502_i5_4_rev",
  "C203_N702_i7_7_rev_N502_i5_5_rev",
  "C203_N702_i7_7_rev_N502_i5_6_rev",
  "C203_N702_i7_7_rev_N502_i5_7_rev",
  "C203_N702_i7_7_rev_N502_i5_8_rev",
  "C203_N702_i7_8_rev_N502_i5_1_rev",
  "C203_N702_i7_8_rev_N502_i5_2_rev",
  "C203_N702_i7_8_rev_N502_i5_3_rev",
  "C203_N702_i7_8_rev_N502_i5_4_rev",
  "C203_N702_i7_8_rev_N502_i5_5_rev",
  "C203_N702_i7_8_rev_N502_i5_6_rev",
  "C203_N702_i7_8_rev_N502_i5_7_rev",
  "C203_N702_i7_8_rev_N502_i5_8_rev",
  "C203_N702_i7_9_rev_N502_i5_1_rev",
  "C203_N702_i7_9_rev_N502_i5_2_rev",
  "C203_N702_i7_9_rev_N502_i5_3_rev",
  "C203_N702_i7_9_rev_N502_i5_4_rev",
  "C203_N702_i7_9_rev_N502_i5_5_rev",
  "C203_N702_i7_9_rev_N502_i5_6_rev",
  "C203_N702_i7_9_rev_N502_i5_7_rev",
  "C203_N702_i7_9_rev_N502_i5_8_rev"
]

SCCAPS_SMPS_REF: "resource/caps_mm9_lambda.fa"